### ISSUE TITLE
how to set query length? 

### ISSUE THREAD

**Issue by fusionfoto** [rzwink/pjm_dataminer#2]
When running a query like this:

python fetch_pjm.py -u rt_unverified_hrl_lmps -f stdout

pr 

python fetch_pjm.py -u rt_unverified_hrl_lmps -f json

the output is limited to 25 lines of output, when the website data explorer is showing over 13,000 lines of data for the same query. 

Where is this limit set?  There doesn't appear to be a page or length option in the help list. 

thanks in advance

**Comment by rzwink** [comment]
While this is an old issue, FYI, the script has been updated to support pagination.
